import Head from "next/head";


export const Meta = () => {
    return (
      <>
      <Head>
        <title>都道府県人口グラフ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/japan.jpeg" />
      </Head>
        
      </>
    );
  };